apiVersion: v2
name: myrancher
description: A simple rancher rest api query app
icon: https://brand.suse.com/assets/img/brand/logo-horizontal-02.png

sources:
  - https://github.com/bjin01/myrancher

maintainers: # (optional)
  - name: Bo Jin
    email: bo.jin@suse.com
    url: https://github.com/bjin01/myrancher
type: application

version: 0.1.4

appVersion: 2.0.0
